version: "3.7"
services:
    mariadb:
        build: requirements/mariadb/
        volumes:
            - mariadb:/var/lib/mysql
        env_file: .env
        networks:
            - inc_network
        container_name: mariadb
        restart: always
    wordpress:
        build: requirements/wordpress/
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - mariadb
        env_file: .env
        networks:
            - inc_network
        container_name: wordpress
        restart: always
    nginx:
        build: requirements/nginx/
        volumes:
            - wordpress:/var/www/html
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file: .env
        container_name: nginx
        networks:
            - inc_network
        restart: always

networks:
    inc_network:
        name: inc_network
        driver: bridge
volumes:
    mariadb:
        driver: local
        name: mariadb
        driver_opts:
            o: bind
            type: none
            device: /home/jbenjy/data/mariadb
    wordpress:
        driver: local
        name: wordpress
        driver_opts:
            o: bind
            type: none
            device: /home/jbenjy/data/wordpress
