version: "3"
services:
    mariadb:
        image: mariadb
        build: ./requirements/mariadb
        volumes:
            - ./requirements/mariadb:/var/lib/mysql
        env_file: .env
        restart: always
    wordpress:
        image: wordpress
        build: ./requirements/wordpress
        volumes:
            - ./requirements/wordpress:/var/www/html
        depends_on:
            - mariadb
        env_file: .env
        restart: always
    nginx:
        image: nginx
        build: ./requirements/nginx
        volumes:
            - ./requirements/nginx:/etc/nginx/conf.d
            - ./requirements/wordpress:/var/www/html
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file: .env
        restart: always