version: "3"
services:
    mariadb:
        image: mariadb
        build: ./requirements/mariadb
        volumes:
            - ./mariadb:/var/lib/mysql
        env_file: .env
        restart: always
    wordpress:
        image: wordpress
        build: ./requirements/wordpress
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - mariadb
        env_file: .env
        restart: always
    nginx:
        image: nginx:latest
        build: ./requirements/nginx
        volumes:
            - ./wordpress:/var/www/html
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file: .env
        restart: always

