version: "3.7"
services:
    mariadb:
        build: requirements/mariadb/
        volumes:
            - mariadb:/var/lib/mysql
        env_file: .env
        networks:
            - inc_network
        container_name: mariadb
        restart: always
    wordpress:
        build: requirements/wordpress/
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - mariadb
        env_file: .env
        networks:
            - inc_network
        container_name: wordpress
        restart: always
    nginx:
        build: requirements/nginx/
        volumes:
            - wordpress:/var/www/html
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file: .env
        container_name: nginx
        networks:
            - inc_network
        restart: always
    webfront:
        build: requirements/bonus/webfront
        container_name: webfront
        ports:
            - "10000:10000"
        networks:
            - inc_network
        restart: always
    admin:
        build: requirements/bonus/admin
        container_name: admin
        ports:
            - "11000:11000"
        depends_on:
            - nginx
        networks:
            - inc_network
        restart: always
    ftp:
        build: requirements/bonus/ftp
        container_name: ftp
        volumes:
            - wordpress:/var/www/html
        ports:
            - "21:21"
            - "21000:21000"
        networks:
            - inc_network
        env_file: .env
        restart: always
    redis:
        build: requirements/bonus/redis/
        container_name: redis
        ports:
            - 6379:6379
        depends_on:
            - nginx
        networks:
            - inc_network
        restart: always
        env_file:
        - .env

networks:
    inc_network:
        name: inc_network
        driver: bridge
volumes:
    mariadb:
        driver: local
        name: mariadb
        driver_opts:
            o: bind
            type: none
            device: /home/jbenjy/data/mariadb
    wordpress:
        driver: local
        name: wordpress
        driver_opts:
            o: bind
            type: none
            device: /home/jbenjy/data/wordpress
