version: "3"
services:
    mariadb:
        image: mariadb
        build: ./requirements/mariadb
        volumes:
            - ./requirements/mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root_pass
            MYSQL_DATABASE: db_name
            MYSQL_USER: user_name
            MYSQL_PASSWORD: user_pass
        restart: always
    wordpress:
        image: wordpress
        build: ./requirements/wordpress
        volumes:
            - ./requirements/wordpress:/var/www/html
        depends_on:
            - mariadb
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root_pass
            WORDPRESS_DB_NAME: db_name
            WORDPRESS_DB_USER: user_name
            WORDPRESS_DB_PASSWORD: user_pass
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_TABLE_PREFIX: wp_
        restart: always
    nginx:
        image: nginx:alpine
        build: ./requirements/nginx
        volumes:
            - ./requirements/nginx:/etc/nginx/conf.d
            - ./requirements/wordpress:/var/www/html
        ports:
            - "443:443"
        links:
            - wordpress